### ISSUE TITLE
Suggestion to add to readme

### ISSUE THREAD

**Issue by jeroentaverne** [konkotgit/MSX-Spider-Cart#2]
The 32Kbyre EPROM occupies address 4000h to BFFFh in the address space because it is using CS1 as read enable. A14 will be high from 4000h to 7FFFh and low from 8000h to BFFFh. So A14 actually needs to be inverted. By swapping the two areas no inverter is required. 

BTW: A15 is not connected but actually has the correct levels for both areas, so swapping A14 with A15 is also a solution.

**Comment by konkotgit** [comment]
Added. Thank you.
